// GENDER LIST
export const NAME_CHANGE = 'NAME_CHANGE';
export const GET_GENDER_PENDING = 'GET_GENDER_PENDING';
export const GET_GENDER_SUCCESS = 'GET_GENDER_SUCCESS';
export const GET_GENDER_FAILURE = 'GET_GENDER_FAILURE';
export const ADD_PERSON = 'ADD_PERSON'

// NAME REGISTRATION
export const REGISTER_GENDER_SELECT = 'REGISTER_GENDER_SELECT';
export const REGISTER_NAME_CHANGE = 'REGISTER_NAME_CHANGE';

export const POST_GENDER_PENDING = 'POST_GENDER_PENDING';
export const POST_GENDER_SUCCESS = 'POST_GENDER_SUCCESS';
export const POST_GENDER_FAILURE = 'POST_GENDER_FAILURE';