export const FETCH_USER = 'FETCH_USER';
export const PROJECTS_REQUESTED = 'PROJECTS_REQUESTED';
export const PROJECTS_RECEIVED = 'PROJECTS_RECEIVED';
export const PROJECTS_ERROR = 'PROJECTS_ERROR';
export const CREATE_PROJECT = 'CREATE_PROJECT';