export const GET_SOURCE = 'GET_SOURCE';
export const SELECT_SOURCE = 'SELECT_SOURCE';
export const CHANGE_SEARCH_TERM = 'CHANGE_SEARCH_TERM';

export const CHANGE_PAGE = 'CHANGE_PAGE';

export const SEARCH_ARTICLE_REQUEST = 'SEARCH_ARTICLE_REQUEST';
export const SEARCH_ARTICLE_SUCCESS = 'SEARCH_ARTICLE_SUCCESS';
export const SEARCH_ARTICLE_FAILURE = 'SEARCH_ARTICLE_FAILURE';

export const GET_ARTICLES_REQUEST = 'GET_ARTICLES_REQUEST';
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS';
export const GET_ARTICLES_FAILURE = 'GET_ARTICLES_FAILURE';
